version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    
  app:
    image: dannyhf/devops-for-programmers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c 'sleep 3 && npm test'