version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    
  app:
    image: dannyhf/devops-for-programmers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - db
    command: bash -c 'sleep 3 && npm test'
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_HOST: ${DATABASE_HOST:-db}