version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: bash -c 'sleep 3 && npm run dev'
    volumes:
    - ./app:/app
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_HOST: db

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres  

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app