name: on-push-workflow
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install make
        run: sudo apt install make

      - name: Install curl
        run: sudo apt install curl

      - name: Install docker
        run: curl -sSL https://get.docker.com/ | sudo sh

      - name: Run test
        run: make test


  push-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: dannyhf/devops-for-programmers-project-74:latest
